// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPG_MVC.Context;

#nullable disable

namespace RPG_MVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230622183535_ArmaEImagensInseridos")]
    partial class ArmaEImagensInseridos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("RPG_MVC.Models.Arma", b =>
                {
                    b.Property<int>("ArmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ataque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("ArmaId");

                    b.ToTable("Armas");
                });

            modelBuilder.Entity("RPG_MVC.Models.Inimigo", b =>
                {
                    b.Property<int>("InimigoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experiencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<int>("Moedas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MpMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("InimigoId");

                    b.ToTable("Inimigos");
                });

            modelBuilder.Entity("RPG_MVC.Models.Jogador", b =>
                {
                    b.Property<int>("JogadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArmaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defesa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experiencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Forca")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HpMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagem")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("Moedas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MpMax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("JogadorId");

                    b.HasIndex("ArmaId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("RPG_MVC.Models.Jogador", b =>
                {
                    b.HasOne("RPG_MVC.Models.Arma", "Arma")
                        .WithMany()
                        .HasForeignKey("ArmaId");

                    b.Navigation("Arma");
                });
#pragma warning restore 612, 618
        }
    }
}
